---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/gitea
  - ../base/immich
  - ../base/media-server
  - ../base/redirector
  - ../base/searxng
  - ../base/vaultwarden
  - resources/ingressroute.yaml
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - configs/gitea-app-ini.env
    name: gitea-app-ini-env
    namespace: gitea

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - git.home.arpa
    target:
      kind: Certificate
      name: gitea
      namespace: gitea
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - photos.home.arpa
    target:
      kind: Certificate
      name: immich
      namespace: immich
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - lidarr.home.arpa
    target:
      kind: Certificate
      name: lidarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - nzbget.home.arpa
    target:
      kind: Certificate
      name: nzbget
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - ombi.home.arpa
    target:
      kind: Certificate
      name: ombi
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - prowlarr.home.arpa
    target:
      kind: Certificate
      name: prowlarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - radarr.home.arpa
    target:
      kind: Certificate
      name: radarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - search.home.arpa
    target:
      kind: Certificate
      name: searxng
      namespace: searxng
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - sonarr.home.arpa
    target:
      kind: Certificate
      name: sonarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - passwords.home.arpa
    target:
      kind: Certificate
      name: vaultwarden
      namespace: vaultwarden
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: CronJob
      namespace: gitea
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/fsGroup
        value: 983
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsUser
        value: 989
    target:
      kind: CronJob
      namespace: vaultwarden
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: Deployment
      name: gitea
      namespace: gitea
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: !!str 1
            memory: 2Gi
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 987
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 987
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 994
    target:
      kind: Deployment
      name: immich-machine-learning
      namespace: immich
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 987
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 987
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 994
    target:
      kind: Deployment
      name: immich-postgres
      namespace: immich
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /dev/dri
          name: dri
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 987
      - op: add
        path: /spec/template/spec/securityContext/supplementalGroups
        value:
          - 44  # video
          - 105 # render
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 987
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 994
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          hostPath:
            path: /dev/dri
            type: Directory
          name: dri
    target:
      kind: Deployment
      name: immich-server
      namespace: immich
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TZ
          value: Europe/London
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 996
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 996
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 999
    target:
      kind: Deployment
      namespace: media
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/env/-
        value:
          name: TZ
          value: Europe/London
    target:
      kind: Deployment
      name: ombi
      namespace: media
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SEARXNG_BASE_URL
          value: https://search.home.arpa
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TZ
          value: Europe/London
    target:
      kind: Deployment
      name: searxng
      namespace: searxng
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 983
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 989
    target:
      kind: Deployment
      namespace: vaultwarden
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`git.home.arpa`)
    target:
      kind: IngressRoute
      name: gitea
      namespace: gitea
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`photos.home.arpa`)
    target:
      kind: IngressRoute
      name: immich
      namespace: immich
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`search.home.arpa`)
    target:
      kind: IngressRoute
      name: searxng
      namespace: searxng
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`passwords.home.arpa`)
    target:
      kind: IngressRoute
      name: vaultwarden
      namespace: vaultwarden
