---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/gitea
  - ../base/linkerd-viz
  - ../base/nullclaw
  - ../base/redirector
  - ../base/vaultwarden
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - configs/gitea-app-ini.env
    name: gitea-app-ini-env
    namespace: gitea

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - git.home.arpa
    target:
      kind: Certificate
      namespace: gitea
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - claw.home.arpa
    target:
      kind: Certificate
      namespace: nullclaw
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - passwords.home.arpa
    target:
      kind: Certificate
      namespace: vaultwarden
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: CronJob
      namespace: gitea
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/fsGroup
        value: 983
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsUser
        value: 989
    target:
      kind: CronJob
      namespace: vaultwarden
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: Deployment
      name: gitea
      namespace: gitea
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 983
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 989
    target:
      kind: Deployment
      namespace: vaultwarden
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`git.home.arpa`)"
    target:
      kind: IngressRoute
      namespace: gitea
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: "Host(`passwords.home.arpa`)"
    target:
      kind: IngressRoute
      namespace: vaultwarden
