---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  name: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gitea.example.com`)
      middlewares:
        - name: ip-allowlist
          namespace: traefik
        - name: security-headers
          namespace: traefik
      services:
        - name: gitea-http
          port: 3000
  tls:
    secretName: gitea-tls
