---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  name: gitea-http
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea-valkey
  name: gitea-valkey
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: valkey
      port: 6379
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea-valkey
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea-valkey-headless
  name: gitea-valkey-headless
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: valkey
      port: 6379
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea-valkey
  type: ClusterIP
