---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-allowlist-internal
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.0/24
      - 192.168.4.0/24
      - 2a0b:9401:8b:1::/64
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: retry
  namespace: traefik
spec:
  retry:
    attempts: 6
    initialInterval: 2s
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    customResponseHeaders:
      Permissions-Policy: geolocation=(), microphone=(), camera=()
      X-Robots-Tag: noindex, nofollow
    frameDeny: true
    referrerPolicy: strict-origin-when-cross-origin
    # stsIncludeSubdomains: true
    # stsPreload: true
    # stsSeconds: 31536000
