---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: letsencrypt-production
spec:
  acme:
    email: certificates@osborn.io
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - kind: Gateway
                name: ingress
                namespace: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: letsencrypt-staging
spec:
  acme:
    email: certificates@osborn.io
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - kind: Gateway
                name: ingress
                namespace: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: ownca
spec:
  ca:
    secretName: ownca-intermediate-ca
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: selfsigned
spec:
  selfSigned: {}
