---
version: 2

updates:
  - package-ecosystem: docker
    directories:
      - /**/resources
    groups:
      immich:
        patterns:
          - immich-app/*
      valkey:
        patterns:
          - valkey-io/valkey
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
