# yamllint disable rule:line-length
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-instagram
  namespace: redirector
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`instagram.com`) || Host(`www.instagram.com`)
      middlewares:
        - name: ip-allowlist
      services:
        - name: redirector
          port: 80
  tls:
    secretName: instagram-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-medium
  namespace: redirector
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`medium.com`) || Host(`www.medium.com`)
      middlewares:
        - name: ip-allowlist
      services:
        - name: redirector
          port: 80
  tls:
    secretName: medium-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-skimresources
  namespace: redirector
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`go.skimresources.com`)
      middlewares:
        - name: ip-allowlist
      services:
        - name: redirector
          port: 80
  tls:
    secretName: skimresources-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-twitter
  namespace: redirector
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`twitter.com`) || Host(`www.twitter.com`) || Host(`www.x.com`) || Host(`x.com`)
      middlewares:
        - name: ip-allowlist
      services:
        - name: redirector
          port: 80
  tls:
    secretName: twitter-tls
