# yamllint disable rule:line-length
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nullclaw
  namespace: nullclaw
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nullclaw.home.arpa`)
      middlewares:
        - name: ip-allowlist
      services:
        - name: nullclaw
          port: 80
  tls:
    secretName: nullclaw-tls
