---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-instagram
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`instagram.com`) || HostRegexp(`^[^.]+\.instagram\.com$`)
      middlewares:
        - name: ip-allowlist
          namespace: traefik
        - name: security-headers
          namespace: traefik
      services:
        - name: redirector
          port: 80
  tls:
    secretName: instagram-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-medium
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`medium.com`) || HostRegexp(`^[^.]+\.medium\.com$`)
      middlewares:
        - name: ip-allowlist
          namespace: traefik
        - name: security-headers
          namespace: traefik
      services:
        - name: redirector
          port: 80
  tls:
    secretName: medium-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-twitter
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`twitter.com`) || HostRegexp(`^[^.]+\.twitter\.com$`)
      middlewares:
        - name: ip-allowlist
          namespace: traefik
        - name: security-headers
          namespace: traefik
      services:
        - name: redirector
          port: 80
  tls:
    secretName: twitter-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirector-x
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`x.com`) || HostRegexp(`^[^.]+\.x\.com$`)
      middlewares:
        - name: ip-allowlist
          namespace: traefik
        - name: security-headers
          namespace: traefik
      services:
        - name: redirector
          port: 80
  tls:
    secretName: x-com-tls
