---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirector
spec:
  rules:
    - host: instagram.com
      http:
        paths:
          - backend:
              service:
                name: redirector
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "*.instagram.com"
      http:
        paths:
          - backend:
              service:
                name: redirector
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: medium.com
      http:
        paths:
          - backend:
              service:
                name: redirector
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "*.medium.com"
      http:
        paths:
          - backend:
              service:
                name: redirector
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: x.com
      http:
        paths:
          - backend:
              service:
                name: redirector
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "*.x.com"
      http:
        paths:
          - backend:
              service:
                name: redirector
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - instagram.com
        - "*.instagram.com"
      secretName: instagram-com-tls
    - hosts:
        - medium.com
        - "*.medium.com"
      secretName: medium-com-tls
    - hosts:
        - x.com
        - "*.x.com"
      secretName: x-com-tls
