---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - resources/certificate.yaml
  - resources/httproute.yaml
  - resources/networkpolicy.yaml
  - resources/referencegrant.yaml
