---
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-redirects-nginx
  namespace: domain-redirects
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 8080;
        server_name x.com *.x.com;

        return 301 https://xcancel.com$request_uri;
      }

      # Default server to handle health checks
      server {
        listen 8080 default_server;
        server_name _;

        location /healthz {
          return 200 "OK\n";
          add_header Content-Type text/plain;
        }

        location / {
          return 404;
        }
      }
    }
