---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redirector

resources:
  - resources/certificate.yaml
  - resources/deployment.yaml
  - resources/httproute.yaml
  - resources/namespace.yaml
  - resources/service.yaml
  - resources/sopssecret.yaml

configMapGenerator:
  - files:
      - configs/nginx.conf
    name: redirector-nginx
