---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/certificate.yaml
  - resources/deployment.yaml
  - resources/ingressroute.yaml
  - resources/middleware.yaml
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  # - resources/persistentvolume.yaml
  # - resources/persistentvolumeclaim.yaml
  - resources/service.yaml

# configMapGenerator:
#   - envs:
#       - configs/zeptoclaw.env
#     name: zeptoclaw
#     namespace: claw
#     options:
#       labels:
#         app.kubernetes.io/component: zeptoclaw
#         app.kubernetes.io/instance: claw
#         app.kubernetes.io/name: zeptoclaw
