---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - resources/cronjob.yaml
  - resources/httproute.yaml # TODO: use Ingress
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/service.yaml
  - resources/sopssecret.yaml
  - resources/deployment.yaml
