---
kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: false
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  name: traefik
