apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik-docker
  name: traefik-docker
  namespace: traefik
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:+lqEKyWVWG824Q==,iv:fViL61sjOkng4+VCSLo171Tyw22COFlSvp2HcmsQxBU=,tag:YfiBPpuQHmetyVFrBM1r4Q==,type:str]
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:R/EDl/YgeOJHO8vgEcRA6C7xaAQh8BOX5w2MKhI32ucHzGRSJacKE+7kz1JwjH4c/HDWV1QkxLSBPsmUhz6FUexIZKfUxWwgnVOpy3eDPpShzeIgqwmEGexdUWk+FnCOJfO3eQrKezJ3EFfoXlfJ7uEuSu1JD0XFTn6IYCYFpDqP3C27bPeBNurfkAxeeRVDi2bXL+U=,iv:oQWTwUsjTo8HkpM0rc1HZXhokZjzl0T7QgMBIob+FjQ=,tag:AwEMJx1LjL8+m1D97c0J+g==,type:str]
      type: ENC[AES256_GCM,data:QOkZrHgTTD5159uyYEkvresMLNnloxZmrWu16HMh,iv:OAr4HZ03Xc82TLhDpMavrVj2kYRglZBtAzNDfGUZw7k=,tag:DwPjxoJZE4T/7YJzYewonA==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa0RQa2tUQk5NWXBVaUdU
        UUw3b1Njd0NEZXc2OXN0TVRGZThJY25mZnpjCjJPZVY1YWdtSUZtc0p3UWhVcjhv
        MFZoR0dwL3BXbHJ1WDhmbzNSU2F4K28KLS0tIG5qcEpLcUtRS2ZCYmNLN1gzdzQ1
        SDRETTFIZHhkZWplaWZSTldQRjB4alkKXRd7x/z5LVdjdodmjhIIEd5hvRvON9hL
        Oanq6s6kRtTqjtEaWf00qvbTJ4yxHT2Mtt5rve6Bt9Q3KWt3adBxyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T08:44:57Z"
  mac: ENC[AES256_GCM,data:rVHDZm2vWaF2oLctlvinKo0AvyDuAoqF66FqueV5uY7ImCH8uPdym6WG4nWcCp+acFbRUXc+zPkQvB1vaX2zDMwuvLizlTANCkxiDB+RLQSLkeTTNUTbzCIxqqOZ30sfvfrZUJlYSjmZVnze+3mWjfIfnjsoHv9zMzYN726wLGc=,iv:xJmye7blsec858gQ6JW9gwGnrRkDRT71hUYxZgUW2Gs=,tag:tNDR3ZFty4DFbQIr1BlxqA==,type:str]
  encrypted_suffix: Templates
  version: 3.11.0
