---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: domain-redirects

resources:
  - resources/certificate.yaml
  - resources/configmap.yaml
  - resources/deployment.yaml
  - resources/ingress.yaml
  - resources/namespace.yaml
  - resources/service.yaml
