---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - ../../base
  - resources/sopssecret.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-ip-allowlist-internal@kubernetescrd
      - op: add
        path: /spec/rules/0/host
        value: passwords.home.arpa
    target:
      kind: Ingress
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsUser
        value: 989
    target:
      kind: Deployment

configMapGenerator:
  - behavior: merge
    literals:
      - DOMAIN=https://passwords.home.arpa
    name: vaultwarden
