# yamllint disable rule:line-length
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts/
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/dataplane-mode: ambient
    pod-security.kubernetes.io/enforce: restricted
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 39.0.2
  install:
    remediation:
      retries: 3
  interval: 1h
  upgrade:
    crds: CreateReplace
  values:
    certificatesResolvers:
      letsencrypt:
        acme:
          keyType: EC256
          profile: shortlived
          storage: /data/acme.json
          tlsChallenge: !!str true
    deployment:
      podAnnotations:
        ambient.istio.io/bypass-inbound-capture: !!str true
      revisionHistoryLimit: 0
    experimental:
      otlpLogs: true
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    ingressClass:
      enabled: false
    ingressRoute:
      dashboard:
        enabled: true
        # entryPoints:
        #   - websecure
        # middlewares:
        #   - name: ip-allowlist
        #     namespace: traefik
        #   - name: security-headers
        #     namespace: traefik
        # tls:
        #   secretName: traefik-dashboard-tls
    logs:
      general:
        otlp:
          enabled: true
          grpc:
            enabled: true
            endpoint: api.uptrace.dev:4317
    metrics:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: api.uptrace.dev:4317
    persistence:
      enabled: true
      storageClass: openebs-hostpath
    ports:
      traefik:
        expose:
          default: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    service:
      spec:
        externalTrafficPolicy: Local
    tracing:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: api.uptrace.dev:4317
    updateStrategy:
      type: Recreate
  valuesFrom:
    - kind: Secret
      name: helm-values
      targetPath: logs.general.otlp.grpc.headers.uptrace-dsn
      valuesKey: uptrace_dsn
    - kind: Secret
      name: helm-values
      targetPath: metrics.otlp.grpc.headers.uptrace-dsn
      valuesKey: uptrace_dsn
    - kind: Secret
      name: helm-values
      targetPath: tracing.otlp.grpc.headers.uptrace-dsn
      valuesKey: uptrace_dsn
