---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redirector

resources:
  - resources/certificate.yaml
  - resources/deployment.yaml
  - resources/ingressroute.yaml
  - resources/middleware.yaml
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  - resources/service.yaml
  - resources/sopssecret.yaml

configMapGenerator:
  - files:
      - configs/nginx.conf
      - configs/redirect.js
    name: redirector-nginx
