---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tombstone-osborn-io
  namespace: flux-system
spec:
  dnsNames:
    - tombstone.osborn.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: tombstone-osborn-io-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hook
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tombstone.osborn.io`) && PathPrefix(`/hook/`)
      middlewares:
        - name: hook-ip-allowlist
      services:
        - name: notification-controller
          port: 80
  tls:
    secretName: tombstone-osborn-io-tls
---
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hook-ip-allowlist
  namespace: flux-system
spec:
  ipAllowList:
    sourceRange:
      - 140.82.112.0/20
      - 143.55.64.0/20
      - 185.199.108.0/22
      - 192.30.252.0/22
      - 2606:50c0::/32
      - 2a0a:a440::/29
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-acme-solver
  namespace: flux-system
spec:
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8089
          protocol: TCP
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: !!str true
  policyTypes:
    - Ingress
