---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - flux-uptrace.yaml
  - flux-webhook.yaml
  - istio-system.yaml
  - metallb.yaml
  - traefik.yaml
