---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  dnsNames:
    - traefik.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  secretName: traefik-dashboard-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-allowlist
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.2/31
      - 192.168.1.4/30
      - 192.168.1.8/29
      - 192.168.1.16/28
      - 192.168.1.32/27
      - 192.168.1.64/26
      - 192.168.1.128/25
      - 192.168.4.0/24
      - 2a0b:9401:8b:1::/64
      - 2a0b:9401:8b:4::/64
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
spec:
  headers:
    customResponseHeaders:
      Permissions-Policy: geolocation=(), microphone=(), camera=()
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-Robots-Tag: noindex, nofollow
      X-XSS-Protection: 1; mode=block
