---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard
spec:
  dnsNames:
    - traefik.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  secretName: traefik-dashboard-tls
