---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - resources/clusterrole.yaml
  - resources/clusterrolebinding.yaml
  - resources/deployment.yaml
  - resources/gateway.yaml
  - resources/gatewayclass.yaml
  - resources/ingressclass.yaml
  - resources/namespace.yaml
  - resources/service.yaml
  - resources/serviceaccount.yaml
  - resources/sopssecret.yaml
