---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - resources/gateway.yaml
  - resources/gatewayclass.yaml
  - resources/httproute.yaml
  - resources/middleware.yaml
