# yamllint disable rule:line-length
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsUser
        value: 987
    target:
      kind: Deployment
      name: gitea
  - patch: |-
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
        value: traefik-ip-allowlist-internal@kubernetescrd
      - op: replace
        path: /spec/rules/0/hostname
        value: git.home.arpa
    target:
      kind: Ingress
