---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tombstone-osborn-io
spec:
  dnsNames:
    - tombstone.osborn.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: tombstone-osborn-io-tls
