---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-webhook
spec:
  hostnames:
    - tombstone.osborn.io
  parentRefs:
    - kind: Gateway
      name: traefik
      namespace: traefik
      sectionName: websecure
  rules:
    - backendRefs:
        - name: notification-controller
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /hook/
