---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-webhook
spec:
  hostnames:
    - tombstone.osborn.io
  parentRefs:
    - kind: Gateway
      name: ingress
      namespace: istio-gateways
  rules:
    - backendRefs:
        - name: notification-controller
          port: 80
      filters:
        - responseHeaderModifier:
            set:
              - name: Permissions-Policy
                value: geolocation=(), microphone=(), camera=()
              - name: Referrer-Policy
                value: strict-origin-when-cross-origin
              - name: X-Content-Type-Options
                value: nosniff
              - name: X-Frame-Options
                value: DENY
              - name: X-Robots-Tag
                value: noindex, nofollow
              - name: X-XSS-Protection
                value: 1; mode=block
          type: ResponseHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /hook/
