---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-acme-solver
  namespace: flux-system
spec:
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - port: 8089
          protocol: TCP
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: !!str true
  policyTypes:
    - Ingress
