---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: ingress
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/part-of: istio
    istio: ingress
    istio.io/dataplane-mode: none
  name: ingress
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ingress
      istio: ingress
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: !!str 15020
        prometheus.io/scrape: !!str true
        sidecar.istio.io/inject: !!str true
      labels:
        app: ingress
        app.kubernetes.io/instance: ingress
        app.kubernetes.io/name: ingress
        app.kubernetes.io/part-of: istio
        istio: ingress
        istio.io/dataplane-mode: none
        sidecar.istio.io/inject: !!str true
    spec:
      containers:
        - env: []
          image: auto # will be populated at runtime by the mutating webhook
          name: istio-proxy
          ports:
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      securityContext:
        runAsGroup: 1337
        runAsUser: 1337
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: ingress
      terminationGracePeriodSeconds: 30
