---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  commonName: root.linkerd.cluster.local
  duration: 87600h # 10 years
  isCA: true
  issuerRef:
    kind: Issuer
    name: linkerd-trust-anchor
  privateKey:
    algorithm: ECDSA
  secretName: linkerd-trust-anchor
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  commonName: identity.linkerd.cluster.local
  duration: 48h
  isCA: true
  issuerRef:
    kind: Issuer
    name: linkerd-identity-issuer
  privateKey:
    algorithm: ECDSA
  renewBefore: 25h
  secretName: linkerd-identity-issuer
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
