---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

resources:
  - resources/clusterrole.yaml
  - resources/clusterrolebinding.yaml
  - resources/deployment.yaml
  - resources/namespace.yaml
  - resources/role.yaml
  - resources/rolebinding.yaml
  - resources/serviceaccount.yaml
