---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
  name: nextcloud
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/name: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/name: nextcloud
        nextcloud-redis-client: !!str true
    spec:
      containers:
        - env:
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: nextcloud-password
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: nextcloud-username
            - name: NEXTCLOUD_DATA_DIR
              value: /var/www/html/data
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_HOST
              value: nextcloud-postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: nextcloud-postgres
            - name: POSTGRES_USER
              value: nextcloud
            - name: REDIS_HOST
              value: nextcloud-valkey
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: nextcloud-redis
            - name: REDIS_HOST_PORT
              value: !!str 6379
          image: docker.io/library/nextcloud:32.0.5-fpm
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: nextcloud
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - DAC_OVERRIDE
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: false # TODO: true
            runAsNonRoot: false # TODO: true
          volumeMounts:
            - mountPath: /var/www/
              name: nextcloud-main
              subPath: root
            - mountPath: /var/www/html
              name: nextcloud-main
              subPath: html
            - mountPath: /var/www/html/config
              name: nextcloud-main
              subPath: config
            - mountPath: /var/www/html/custom_apps
              name: nextcloud-main
              subPath: custom_apps
            - mountPath: /var/www/html/data
              name: nextcloud-main
              subPath: data
            - mountPath: /var/www/html/themes
              name: nextcloud-main
              subPath: themes
            - mountPath: /var/www/tmp
              name: nextcloud-main
              subPath: tmp
      imagePullSecrets:
        - name: docker-hub
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: nextcloud-main
          persistentVolumeClaim:
            claimName: nextcloud-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-postgres
  name: nextcloud-postgres
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/name: nextcloud-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/name: nextcloud-postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: nextcloud
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: nextcloud-postgres
            - name: POSTGRES_USER
              value: nextcloud
          image: docker.io/library/postgres:17.7
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - nextcloud
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - nextcloud
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            # allowPrivilegeEscalation: false
            # capabilities:
            #   drop:
            #     - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/postgresql
              name: run
            - mountPath: /var/lib/postgresql/data
              name: data
      imagePullSecrets:
        - name: docker-hub
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - emptyDir: {}
          name: run
        - emptyDir: {}
          name: tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: valkey
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-valkey
  name: nextcloud-valkey
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: valkey
      app.kubernetes.io/instance: nextcloud
      app.kubernetes.io/name: nextcloud-valkey
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: valkey
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/name: nextcloud-valkey
    spec:
      containers:
        - args:
            - --appendonly
            - !!str yes
          image: ghcr.io/valkey-io/valkey:9.0.2
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - valkey-cli ping | grep PONG
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: valkey
          ports:
            - containerPort: 6379
              name: valkey
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - valkey-cli ping | grep PONG
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-valkey-data
