---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
  name: nextcloud
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-postgres
  name: nextcloud-postgres
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-postgres-headless
  name: nextcloud-postgres-headless
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-valkey
  name: nextcloud-valkey
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: valkey
      port: 6379
  selector:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-valkey
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-valkey-headless
  name: nextcloud-valkey-headless
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: valkey
      port: 6379
  selector:
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud-valkey
  type: ClusterIP
