---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.home.arpa
    target:
      kind: CronJob
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          link.argocd.argoproj.io/external-link: https://nextcloud.home.arpa
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.home.arpa
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/httpHeaders
        value:
          - name: Host
            value: nextcloud.home.arpa
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
          - nextcloud.home.arpa
    target:
      kind: HTTPRoute
