---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - ../../base
  - resources/ingress.yaml
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - configs/app-ini.env
    name: gitea-app-ini-env

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: Deployment
      name: gitea
