---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - ../../base
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - configs/app-ini.env
    name: gitea-app-ini-env

patches:
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: CronJob
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 981
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 987
    target:
      kind: Deployment
      name: gitea
  - patch: |-
      - op: add
        path: /spec/dnsNames
        value:
          - git.home.arpa
    target:
      kind: Certificate
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-ip-allowlist-internal@kubernetescrd
      - op: add
        path: /spec/hostnames
        value:
          - git.home.arpa
    target:
      kind: HTTPRoute
