---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - ../../base
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    literals:
      - DOMAIN=https://passwords.home.arpa
    name: vaultwarden

patches:
  - patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/fsGroup
        value: 983
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/jobTemplate/spec/template/spec/securityContext/runAsUser
        value: 989
    target:
      kind: CronJob
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 983
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 983
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 989
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/dnsNames
        value:
          - passwords.home.arpa
    target:
      kind: Certificate
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-ip-allowlist-internal@kubernetescrd
      - op: add
        path: /spec/hostnames
        value:
          - passwords.home.arpa
    target:
      kind: HTTPRoute
