---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - ../../base
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    literals:
      - DOMAIN=https://passwords.home.arpa
    name: vaultwarden

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: ownca
          traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect@kubernetescrd,traefik-ip-allowlist-internal@kubernetescrd
          traefik.ingress.kubernetes.io/service.serversscheme: https
      - op: add
        path: /spec/rules/0/host
        value: passwords.home.arpa
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - passwords.home.arpa
            secretName: passwords-home-arpa-tls
    target:
      kind: Ingress
